/**
 * Every user-facing string lives here, keyed by locale.
 * Hebrew is the launch locale; the shape is ready for "en" without touching
 * component code (see t()).
 */
import type { AvailabilityState } from "./constants";

export const LOCALES = ["he", "en"] as const;
export type Locale = (typeof LOCALES)[number];
export const DEFAULT_LOCALE: Locale = "he";

type Dict = Record<string, string>;

const he: Dict = {
  "app.name": "VELTO",
  "app.tagline": "שטחי פרסום חוץ בישראל — חיפוש, השוואה ובקשת זמינות",
  "nav.explore": "מפה",
  "nav.dashboard": "אזור אישי",
  "nav.admin": "ניהול",
  "nav.login": "כניסה",
  "nav.register": "הרשמה",
  "nav.logout": "יציאה",
  "nav.listYourSpace": "בעלי שטחים — פרסמו אצלנו",
  "nav.notifications": "התראות",
  "nav.skipToContent": "דילוג לתוכן הראשי",

  "common.loading": "טוען…",
  "common.save": "שמירה",
  "common.cancel": "ביטול",
  "common.back": "חזרה",
  "common.next": "המשך",
  "common.submit": "שליחה",
  "common.edit": "עריכה",
  "common.delete": "מחיקה",
  "common.close": "סגירה",
  "common.notProvided": "לא צוין",
  "common.unknown": "לא ידוע",
  "common.required": "שדה חובה",
  "common.optional": "רשות",
  "common.from": "החל מ־",
  "common.to": "עד",
  "common.results": "תוצאות",
  "common.error": "אירעה שגיאה. נסו שוב.",
  "common.demoData": "נתוני הדגמה",
  "common.demoDataNote": "רשומה זו נוצרה לצורכי פיתוח והדגמה ואינה מלאי מסחרי מאומת.",

  "map.title": "מפת שטחי הפרסום",
  "map.searchPlaceholder": "חיפוש עיר, רחוב או שם שטח…",
  "map.filters": "מסננים",
  "map.clearFilters": "ניקוי מסננים",
  "map.showResults": "הצגת {count} תוצאות",
  "map.resultsCount": "{count} שטחי פרסום",
  "map.noResults": "לא נמצאו שטחי פרסום באזור זה.",
  "map.noResultsHint": "נסו להרחיב את אזור המפה או לאפס את המסננים.",
  "map.viewAllIsrael": "תצוגת כל הארץ",
  "map.backToBeerSheva": "חזרה לבאר שבע",
  "map.inventoryNote": "מוצגים רק שטחים שקיימים במאגר VELTO.",
  "map.list": "רשימה",

  "filter.city": "עיר",
  "filter.allCities": "כל הערים",
  "filter.assetType": "סוג שטח",
  "filter.availability": "זמינות",
  "filter.dates": "תאריכי קמפיין",
  "filter.priceRange": "טווח מחירים (חודשי)",
  "filter.minPrice": "מינימום",
  "filter.maxPrice": "מקסימום",
  "filter.digitalOnly": "דיגיטלי בלבד",
  "filter.verifiedOnly": "מאומתים בלבד",

  "asset.verification": "אימות",
  "asset.availability": "זמינות",
  "asset.location": "מיקום",
  "asset.specs": "מפרט",
  "asset.commercial": "מסחרי",
  "asset.type": "סוג",
  "asset.dimensions": "מידות",
  "asset.orientation": "כיוון",
  "asset.sides": "מספר צדדים",
  "asset.illumination": "תאורה",
  "asset.digital": "דיגיטלי",
  "asset.static": "סטטי",
  "asset.permit": "רישוי",
  "asset.priceWeekly": "מחיר שבועי",
  "asset.priceMonthly": "מחיר חודשי",
  "asset.priceFrom": "החל מ־",
  "asset.priceNotPublished": "המחיר אינו מפורסם — ניתן לבקש הצעת מחיר",
  "asset.priceEstimateNote": "המחיר הוא הערכה בלבד ואינו מהווה הצעה מחייבת.",
  "asset.minimumBooking": "תקופת הזמנה מינימלית",
  "asset.days": "ימים",
  "asset.extras": "כלול במחיר",
  "asset.production": "הפקה",
  "asset.installation": "התקנה",
  "asset.removal": "פירוק",
  "asset.notIncluded": "לא כלול",
  "asset.owner": "בעל השטח",
  "asset.availabilityPeriods": "חלונות זמינות שהוגדרו",
  "asset.noPeriods": "בעל השטח טרם הגדיר חלונות זמינות.",
  "asset.save": "שמירה לרשימה",
  "asset.unsave": "הסרה מהרשימה",
  "asset.saved": "נשמר",
  "asset.requestAvailability": "בדיקת זמינות ומחיר",
  "asset.requestQuote": "בקשת הצעת מחיר",
  "asset.requestBooking": "בקשת הזמנה",
  "asset.noImages": "לא הועלו תמונות לשטח זה.",
  "asset.backToMap": "חזרה למפה",

  "verify.PENDING": "ממתין לאימות",
  "verify.VERIFIED": "מאומת ע״י VELTO",
  "verify.REJECTED": "נדחה באימות",
  "verify.PENDING.help": "הפרטים דווחו ע״י בעל השטח וטרם אומתו.",
  "verify.VERIFIED.help": "פרטי השטח נבדקו ואומתו ע״י VELTO.",
  "verify.REJECTED.help": "השטח נדחה ואינו מוצג לציבור.",

  "avail.AVAILABLE": "זמין",
  "avail.PARTIAL": "זמין חלקית",
  "avail.OCCUPIED": "תפוס",
  "avail.INACTIVE": "לא פעיל",
  "avail.PENDING_VERIFICATION": "ממתין לאימות",
  "avail.AVAILABLE.help": "פנוי בכל התאריכים שנבחרו.",
  "avail.PARTIAL.help": "חלק מהתאריכים שנבחרו פנויים.",
  "avail.OCCUPIED.help": "התאריכים שנבחרו תפוסים.",
  "avail.INACTIVE.help": "השטח אינו פעיל להזמנות.",
  "avail.PENDING_VERIFICATION.help": "השטח ממתין לאימות VELTO.",

  "type.BILLBOARD": "שלט חוצות",
  "type.DIGITAL_BILLBOARD": "שלט דיגיטלי",
  "type.WALL": "קיר",
  "type.TOTEM": "טוטם",
  "type.BUS_STOP": "תחנת אוטובוס",
  "type.STREET_FURNITURE": "ריהוט רחוב",
  "type.BANNER": "באנר",
  "type.OTHER": "אחר",

  "illum.NONE": "ללא תאורה",
  "illum.FRONTLIT": "תאורה קדמית",
  "illum.BACKLIT": "תאורה אחורית",
  "illum.UNKNOWN": "לא ידוע",

  "permit.UNKNOWN": "לא ידוע",
  "permit.PERMITTED": "בעל רישוי",
  "permit.NOT_PERMITTED": "ללא רישוי",
  "permit.note": "VELTO אינה מאשרת חוקיות שילוט. הסטטוס מדווח ע״י בעל השטח.",

  "status.DRAFT": "טיוטה",
  "status.ACTIVE": "פעיל",
  "status.INACTIVE": "לא פעיל",

  "inquiry.PENDING": "ממתינה למענה",
  "inquiry.RESPONDED": "נענתה",
  "inquiry.CLOSED": "סגורה",
  "intent.AVAILABILITY": "בדיקת זמינות",
  "intent.QUOTE": "הצעת מחיר",
  "intent.BOOKING": "בקשת הזמנה",

  "booking.REQUESTED": "ממתינה לאישור",
  "booking.APPROVED": "מאושרת",
  "booking.REJECTED": "נדחתה",
  "booking.CANCELLED": "בוטלה",
  "booking.COMPLETED": "הושלמה",

  "role.ADVERTISER": "מפרסם",
  "role.MEDIA_OWNER": "בעל שטח",
  "role.ADMIN": "מנהל",

  "auth.login": "כניסה לחשבון",
  "auth.register": "יצירת חשבון",
  "auth.email": "דוא״ל",
  "auth.password": "סיסמה",
  "auth.name": "שם מלא",
  "auth.phone": "טלפון",
  "auth.companyName": "שם החברה",
  "auth.role": "סוג החשבון",
  "auth.roleAdvertiser": "מפרסם / משרד פרסום — מחפש שטחי פרסום",
  "auth.roleOwner": "בעל שטחים — מפרסם מלאי",
  "auth.noAccount": "אין לכם חשבון?",
  "auth.hasAccount": "כבר יש לכם חשבון?",
  "auth.invalidCredentials": "דוא״ל או סיסמה שגויים.",
  "auth.emailTaken": "כתובת הדוא״ל כבר רשומה במערכת.",
  "auth.tooManyAttempts": "יותר מדי ניסיונות כניסה. נסו שוב בעוד מספר דקות.",
  "auth.passwordRule": "לפחות 8 תווים.",
  "auth.loginRequired": "יש להתחבר כדי להמשיך.",

  "dash.overview": "סקירה",
  "dash.myRequests": "הבקשות שלי",
  "dash.myBookings": "ההזמנות שלי",
  "dash.savedAssets": "שטחים שמורים",
  "dash.profile": "פרופיל",
  "dash.myAssets": "השטחים שלי",
  "dash.availability": "זמינות",
  "dash.requests": "בקשות",
  "dash.bookings": "הזמנות",
  "dash.activeRequests": "בקשות פעילות",
  "dash.pendingResponses": "ממתינות למענה",
  "dash.upcomingBookings": "הזמנות קרובות",
  "dash.activeAssets": "שטחים פעילים",
  "dash.pendingRequests": "בקשות שממתינות לכם",
  "dash.confirmedBookings": "הזמנות מאושרות",
  "dash.addAsset": "הוספת שטח פרסום",
  "dash.noRequests": "אין לכם עדיין בקשות.",
  "dash.noRequestsHint": "מצאו שטח במפה ושלחו בקשת זמינות — הבקשות יופיעו כאן.",
  "dash.noBookings": "אין הזמנות להצגה.",
  "dash.noSaved": "שמרו כאן שטחים מעניינים כדי להשוות ביניהם מאוחר יותר.",
  "dash.noAssets": "עדיין לא הוספתם שטחי פרסום.",
  "dash.noAssetsHint": "הוסיפו את השטח הראשון שלכם כדי לקבל פניות ממפרסמים.",
  "dash.respond": "מענה למפרסם",
  "dash.approve": "אישור",
  "dash.reject": "דחייה",
  "dash.cancel": "ביטול",
  "dash.responseSent": "המענה נשלח.",
  "dash.conflict": "לא ניתן לאשר: קיימת כבר הזמנה מאושרת בתאריכים חופפים.",

  "wizard.step": "שלב",
  "wizard.of": "מתוך",
  "wizard.basic": "פרטים בסיסיים",
  "wizard.location": "מיקום",
  "wizard.specs": "מפרט",
  "wizard.pricing": "תמחור",
  "wizard.availability": "זמינות",
  "wizard.images": "תמונות",
  "wizard.review": "סקירה ופרסום",
  "wizard.publish": "פרסום השטח",
  "wizard.saveDraft": "שמירה כטיוטה",
  "wizard.draftSaved": "הטיוטה נשמרה.",
  "wizard.pickOnMap": "לחצו על המפה כדי לסמן את מיקום השטח.",
  "wizard.published": "השטח פורסם וממתין לאימות VELTO.",

  "request.title": "בקשת זמינות ומחיר",
  "request.campaignName": "שם הקמפיין",
  "request.dates": "תאריכי הקמפיין",
  "request.budget": "תקציב משוער",
  "request.message": "הודעה לבעל השטח",
  "request.contact": "פרטי קשר",
  "request.submitted": "הבקשה נשלחה לבעל השטח.",
  "request.submittedHint": "תוכלו לעקוב אחריה באזור האישי.",
  "request.intent": "סוג הפנייה",
  "request.minDaysError": "תקופת ההזמנה קצרה מהמינימום שהוגדר לשטח.",
  "request.pastDateError": "לא ניתן לבחור תאריך שכבר עבר.",
  "request.dateOrderError": "תאריך הסיום חייב להיות אחרי תאריך ההתחלה.",

  "admin.users": "משתמשים",
  "admin.assets": "שטחים",
  "admin.verify": "אימות",
  "admin.approveAsset": "אימות השטח",
  "admin.rejectAsset": "דחיית השטח",
  "admin.deactivate": "השבתה",
  "admin.activate": "הפעלה",
  "admin.reviewNote": "הערת בדיקה",
  "admin.platform": "פעילות בפלטפורמה",

  "notif.empty": "אין התראות חדשות.",
  "notif.markRead": "סימון כנקרא",
};

/** English keys fall back to Hebrew until the English pass is done. */
const en: Dict = {
  "app.tagline": "Outdoor advertising space in Israel - search, compare, request",
  "common.notProvided": "Not provided",
  "common.unknown": "Unknown",
  "avail.AVAILABLE": "Available",
  "avail.PARTIAL": "Partially available",
  "avail.OCCUPIED": "Booked",
  "avail.INACTIVE": "Inactive",
  "avail.PENDING_VERIFICATION": "Pending verification",
  "verify.VERIFIED": "Verified by VELTO",
  "verify.PENDING": "Pending verification",
  "verify.REJECTED": "Rejected",
};

const DICTS: Record<Locale, Dict> = { he, en };

/** Translate. Unknown keys return the key itself so gaps are visible, not silent. */
export function t(key: string, vars?: Record<string, string | number>, locale: Locale = DEFAULT_LOCALE): string {
  const dict = DICTS[locale] ?? he;
  let out = dict[key] ?? he[key] ?? key;
  if (vars) {
    for (const [k, v] of Object.entries(vars)) out = out.replaceAll(`{${k}}`, String(v));
  }
  return out;
}

/** Non-colour glyph for each availability state (accessibility requirement). */
export const AVAILABILITY_GLYPH: Record<AvailabilityState, string> = {
  AVAILABLE: "●",
  PARTIAL: "◐",
  OCCUPIED: "✕",
  INACTIVE: "—",
  PENDING_VERIFICATION: "?",
};
