import { chromium } from '@playwright/test';
const b = await chromium.launch({ executablePath:'/opt/pw-browsers/chromium-1194/chrome-linux/chrome', args:['--enable-unsafe-swiftshader']});
const p = await b.newPage({viewport:{width:1440,height:900}});
p.on('pageerror', e=>console.log('PAGEERROR', e.message.slice(0,200)));
await p.goto('http://localhost:3000/', {waitUntil:'domcontentloaded'});
await p.waitForSelector('[data-asset]', {timeout:20000});
const link = p.locator('[data-asset]').first().getByRole('link');
console.log('link count', await link.count(), 'href', await link.first().getAttribute('href'));
await link.first().click();
await p.waitForTimeout(4000);
console.log('URL', p.url());
console.log('h1', await p.locator('h1').allTextContents());
console.log('body snippet', (await p.locator('body').innerText()).slice(0,300));
await b.close();
